# -*- coding: utf-8 -*-
"""Milestone 1 Evidently Dashboards.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVi0OoCDcJx0lzw1BTMNVBQ7UC1WKo1g
"""

!pip install -U evidently==0.4.25 numpy==1.26.4

from evidently.report import Report
from evidently.metric_preset import DataDriftPreset, DataQualityPreset

# --- Sample data creation ---
import pandas as pd
from sklearn.datasets import load_iris

# Load the built-in Iris dataset
iris = load_iris(as_frame=True)
df = iris.frame

# Split into reference (old) and current (new) data
reference_data = df.sample(frac=0.5, random_state=42)
current_data   = df.sample(frac=0.5, random_state=99)

# --- Evidently report creation ---
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset, DataQualityPreset

# Build and run the report
report = Report(metrics=[
    DataDriftPreset(),
    DataQualityPreset()
])
report.run(reference_data=reference_data, current_data=current_data)

# Display the interactive dashboard in-line
report.show(mode='inline')

report.save_html("data_drift_report.html")