# -*- coding: utf-8 -*-
"""Milestone 1 Evidently Dashboards.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVi0OoCDcJx0lzw1BTMNVBQ7UC1WKo1g
"""

!pip install -U evidently==0.4.25 numpy==1.26.4

from evidently.report import Report
from evidently.metric_preset import DataDriftPreset, DataQualityPreset

# Install kagglehub if not already installed
!pip install kagglehub -q
print("✅ kagglehub installed!")

# --- Plant Disease Dataset Loading ---
import kagglehub
import os
from pathlib import Path
from PIL import Image
import numpy as np
import pandas as pd

# Step 1: Download dataset automatically
print("⬇️ Downloading Plant Disease Dataset...")
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")
print(f"✅ Dataset downloaded to: {path}\n")

# Step 2: Auto-detect folder structure
BASE_PATH = Path(path)

print("📁 Exploring dataset structure...")
all_folders = [item for item in BASE_PATH.rglob('*') if item.is_dir()]

# Find train and valid folders
TRAIN_PATH = None
VALID_PATH = None

for folder in all_folders:
    if folder.name == 'train':
        TRAIN_PATH = folder
    elif folder.name == 'valid':
        VALID_PATH = folder

if not TRAIN_PATH or not VALID_PATH:
    print("❌ Dataset structure:")
    for folder in all_folders[:20]:  # Show first 20 folders
        print(f"   {folder}")
    raise FileNotFoundError("Could not find train/valid folders!")

print(f"✅ Train path: {TRAIN_PATH}")
print(f"✅ Valid path: {VALID_PATH}\n")

class_names = sorted([d.name for d in TRAIN_PATH.iterdir() if d.is_dir()])
print(f"📊 Found {len(class_names)} classes")
print(f"📋 Sample classes: {class_names[:5]}...\n")

# Step 3: Feature extraction function
def extract_image_features(image_path, img_size=(256, 256)):
    try:
        img = Image.open(image_path).convert('RGB')
        img = img.resize(img_size)
        img_array = np.array(img)

        features = {
            'mean_red': img_array[:,:,0].mean(),
            'mean_green': img_array[:,:,1].mean(),
            'mean_blue': img_array[:,:,2].mean(),
            'std_red': img_array[:,:,0].std(),
            'std_green': img_array[:,:,1].std(),
            'std_blue': img_array[:,:,2].std(),
            'brightness': img_array.mean(),
            'contrast': img_array.std(),
            'file_size_kb': os.path.getsize(image_path) / 1024,
        }

        total = features['mean_red'] + features['mean_green'] + features['mean_blue']
        if total > 0:
            features['red_ratio'] = features['mean_red'] / total
            features['green_ratio'] = features['mean_green'] / total
            features['blue_ratio'] = features['mean_blue'] / total

        return features
    except Exception as e:
        return None

# Step 4: Create DataFrame function
def create_dataframe(data_path, sample_per_class=100):
    records = []
    total_processed = 0

    for class_idx, class_name in enumerate(class_names):
        class_path = data_path / class_name
        image_files = list(class_path.glob('*.jpg')) + list(class_path.glob('*.JPG'))

        if len(image_files) > sample_per_class:
            image_files = np.random.choice(image_files, sample_per_class, replace=False)

        print(f"Processing {class_name}: {len(image_files)} images", end='\r')

        for img_path in image_files:
            features = extract_image_features(img_path)
            if features:
                features['class_name'] = class_name
                features['class_id'] = class_idx

                if '___' in class_name:
                    plant, disease = class_name.split('___')
                    features['plant_type'] = plant
                    features['disease_type'] = disease
                    features['is_healthy'] = 1 if disease.lower() == 'healthy' else 0
                else:
                    features['plant_type'] = class_name
                    features['disease_type'] = 'unknown'
                    features['is_healthy'] = 0

                records.append(features)
                total_processed += 1

    print(f"\n✅ Processed {total_processed} images from {len(class_names)} classes")
    return pd.DataFrame(records)

# Step 5: Load data (ADJUST SAMPLE SIZE HERE!)
print("🔄 Loading training data...")
reference_data = create_dataframe(TRAIN_PATH, sample_per_class=100)  # ⚙️ Change this

print("\n🔄 Loading validation data...")
current_data = create_dataframe(VALID_PATH, sample_per_class=50)  # ⚙️ Change this

print(f"\n{'='*60}")
print(f"✅ Reference (Train): {len(reference_data)} samples")
print(f"✅ Current (Valid): {len(current_data)} samples")
print(f"✅ Total Classes: {len(class_names)}")
print(f"{'='*60}\n")

# Display sample data
print("📊 Sample Data Preview:")
print(reference_data.head())
print(f"\n📋 Features: {list(reference_data.columns)}")

# --- Evidently report creation ---
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset, DataQualityPreset

# Build and run the report
report = Report(metrics=[
    DataDriftPreset(),
    DataQualityPreset()
])
report.run(reference_data=reference_data, current_data=current_data)

# Display the interactive dashboard in-line
report.show(mode='inline')

report.save_html("data_drift_report.html")

from google.colab import files

# Download the generated HTML report
files.download('data_drift_report.html')

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Qar-Raz/MLOPS_Project.git
# %cd MLOPS_Project
!git checkout Evidently-Dashboards

!pip install pre-commit

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/MLOPS_Project

!pre-commit install

!cat .git/hooks/pre-commit

!pre-commit run --all-files