name: Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate lowercase tag
        run: |
          IMAGE="ghcr.io/${{ github.repository }}/flora-backend"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=${IMAGE}:latest" >> $GITHUB_ENV

      - name: Debug Tag
        run: echo "Tag -> ${{ env.IMAGE_NAME }}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_NAME }}
